apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  SPRING_LIQUIBASE_USER: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  USERSERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.userServiceSpringDatasourceUsername | b64enc | quote }}
  USERSERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.userServiceSpringDatasourcePassword | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_USERNAME: {{ .Values.keycloakserviceAdminUsername | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_PASSWORD: {{ .Values.keycloakserviceAdminPassword | b64enc | quote }}
  KEYCLOAKSERVICE_TECHNICAL_USERNAME: {{ .Values.keycloakserviceTechnicalUsername | b64enc | quote }}
  KEYCLOAKSERVICE_TECHNICAL_PASSWORD: {{ .Values.keycloakserviceTechnicalPassword | b64enc | quote }}
  ROCKET_TECHNICAL_USERNAME:  {{ .Values.rocketTechnicalUsername  | b64enc | quote }}
  ROCKET_TECHNICAL_PASSWORD:  {{ .Values.rocketTechnicalPassword  | b64enc | quote }}
  ROCKET_SYSTEMUSER_USERNAME: {{ .Values.rocketSystemuserUsername | b64enc | quote }}
  ROCKET_SYSTEMUSER_PASSWORD: {{ .Values.rocketSystemuserPassword | b64enc | quote }}
  {{- $mongourl := printf "mongodb://%s:%s@mongodb.%s:27017/rocketchat?retryWrites=false" .Values.global.rocketchatMongoUsername .Values.global.rocketchatMongoPassword .Release.Namespace }}
  ROCKET_CHAT_MONGO_URL: {{ $mongourl | b64enc | quote }}
  SITE247_LICENSE_KEY: {{ .Values.site24x7LicenseKey | b64enc | quote }}
  ONLINEBERATUNG_SENTRY_DSN: {{ .Values.sentry.dsn | b64enc | quote }}

