{{- if .Values.global.migrationToolEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: migrationtool-secret-{{ .Release.Name }}-env
type: Opaque
data:
  {{- $mongourl := printf "mongodb://%s:%s@mongodb.%s:27017/consulting_types?retryWrites=false" .Values.global.consultingTypeMongoUser .Values.global.consultingTypeMongoPass .Release.Namespace }}
  SPRING_DATA_MONGODB_URI: {{ $mongourl | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  SPRING_DATASOURCE_USERSERVICE_USERNAME: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_DATASOURCE_USERSERVICE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_USERNAME: {{ .Values.keycloakserviceAdminUsername | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_PASSWORD: {{ .Values.keycloakserviceAdminPassword | b64enc | quote }}
  ROCKETCHAT_CONFIG_ADMIN_USERNAME: {{ .Values.rocketAdminUsername | b64enc | quote }}
  ROCKETCHAT_CONFIG_ADMIN_PASSWORD: {{ .Values.rocketAdminPassword | b64enc | quote }}
  SPRING_DATASOURCE_TENANTSERVICE_USERNAME: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_DATASOURCE_TENANTSERVICE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  SPRING_DATASOURCE_AGENCYSERVICE_USERNAME: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_DATASOURCE_AGENCYSERVICE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  SPRING_DATASOURCE_CONSULTINGTYPESERVICE_USERNAME: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_DATASOURCE_CONSULTINGTYPESERVICE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  USERS_JITSI_TECHNICAL_PASSWORD: {{ .Values.jitsiTechnicalPassword | b64enc | quote }}
  USERS_JITSI_TECHNICAL_EMAIL: {{ .Values.jitsiTechnicalEmail | b64enc | quote }}
  USERS_JITSI_TECHNICAL_TENANTID: {{ .Values.jitsiTechnicalTenantId | b64enc | quote }}
  USERS_PUBLIC_PLAN_TECHNICAL_PASSWORD: {{ .Values.publicPlanTechnicalPassword | b64enc | quote }}
  USERS_PUBLIC_PLAN_TECHNICAL_EMAIL: {{ .Values.publicPlanTechnicalEmail | b64enc | quote }}
  USERS_PUBLIC_PLAN_TECHNICAL_TENANTID: {{ .Values.publicPlanTechnicalTenantId | b64enc | quote }}
{{- end }}