{{- if .Values.global.counselingToolsEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: counselingtoolsservice
  name: counselingtoolsservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: counselingtoolsservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/database_network: "true"
        io.kompose.network/frontend_network: "true"
        io.kompose.network/service_network: "true"
        io.kompose.service: counselingtoolsservice
    spec:
      hostAliases:
        - ip: {{ .Values.global.dockerHostIp }}
          hostnames:
            - {{ .Values.global.domainName }}
      initContainers:
        - name: wait-for-keycloak
          image: busybox
          command: [ "sh", "-c", "until nc -z keycloak 8080 > /dev/null; do echo Waiting for keycloak.; sleep 5; done;" ]
      containers:
        - env:
            - name: IDENTITY_OPENID_CONNECT_URL
              valueFrom:
                configMapKeyRef:
                  key: IDENTITY_OPENID_CONNECT_URL
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: IDENTITY_OTP_URL
              valueFrom:
                configMapKeyRef:
                  key: IDENTITY_OTP_URL
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: USER_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: USER_SERVICE_API_URL
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: USER_ADMIN_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: USER_ADMIN_SERVICE_API_URL
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_API_URL
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_PUBLIC_URL
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_PROXY_WHITELISTED
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_PROXY_WHITELISTED
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_PROXY_HOST
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_PROXY_HOST
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_API_KEY
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_APPSAPP_ID
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_APPSAPP_ID
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_APPS_QUERY_ID
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_APPS_QUERY_ID
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_CONSULTANTVIEWAPP_ID
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_CONSULTANTVIEWAPP_ID
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_CONSULTANTVIEWAPP_QUERY_ID
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_CONSULTANTVIEWAPP_QUERY_ID
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_EXPORTAPP_ID
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_EXPORTAPP_ID
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: BUDIBASE_EXPORT_QUERY_ID
              valueFrom:
                configMapKeyRef:
                  key: BUDIBASE_EXPORT_QUERY_ID
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: APP_BASE_URL
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_CONFIG_ADMIN_CLIENTID
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_CONFIG_ADMIN_CLIENTID
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_CONFIG_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_CONFIG_ADMIN_PASSWORD
                  name: counselingtoolsservice-secret-{{ .Release.Name }}-env
            - name: KEYCLOAK_CONFIG_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_CONFIG_ADMIN_USERNAME
                  name: counselingtoolsservice-secret-{{ .Release.Name }}-env
            - name: KEYCLOAKSERVICE_TECHNICAL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAKSERVICE_TECHNICAL_PASSWORD
                  name: counselingtoolsservice-secret-{{ .Release.Name }}-env
            - name: KEYCLOAKSERVICE_TECHNICAL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAKSERVICE_TECHNICAL_USERNAME
                  name: counselingtoolsservice-secret-{{ .Release.Name }}-env
            - name: KEYCLOAK_CONFIG_APP_CLIENTID
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_CONFIG_APP_CLIENTID
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_AUTH_SERVER_URL
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_CORS
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_CORS
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_PRINCIPAL_ATTRIBUTE
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_PRINCIPAL_ATTRIBUTE
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_REALM
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_RESOURCE
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_RESOURCE
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: CSRF_COOKIE_PROPERTY
              valueFrom:
                configMapKeyRef:
                  key: CSRF_COOKIE_PROPERTY
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: CSRF_HEADER_PROPERTY
              valueFrom:
                configMapKeyRef:
                  key: CSRF_HEADER_PROPERTY
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: CSRF_WHITELIST_HEADER_PROPERTY
              valueFrom:
                configMapKeyRef:
                  key: CSRF_WHITELIST_HEADER_PROPERTY
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: COUNSELINGTOOLSSERVICE_SPRING_DATASOURCE_PASSWORD
                  name: counselingtoolsservice-secret-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: counselingtoolsservice-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: COUNSELINGTOOLSSERVICE_SPRING_DATASOURCE_USERNAME
                  name: counselingtoolsservice-secret-{{ .Release.Name }}-env
            - name: SPRING_LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_LIQUIBASE_PASSWORD
                  name: counselingtoolsservice-secret-{{ .Release.Name }}-env
            - name: SPRING_LIQUIBASE_USER
              valueFrom:
                secretKeyRef:
                  key: SPRING_LIQUIBASE_USER
                  name: counselingtoolsservice-secret-{{ .Release.Name }}-env
          image: {{ .Values.counselingToolsServiceImageName }}:{{ .Values.counselingToolsServiceImageVersion }}
          name: counselingtoolsservice
          ports:
            - containerPort: 8080
          {{- if .Values.counselingtoolsservice }}
          {{- if .Values.counselingtoolsservice.resources }}
          resources:
            {{- if .Values.counselingtoolsservice.resources.requests }}
            requests:
              {{- if .Values.counselingtoolsservice.resources.requests.memory }}
              memory: {{  .Values.counselingtoolsservice.resources.requests.memory }}
              {{- end}}
              {{- if .Values.counselingtoolsservice.resources.requests.cpu }}
              cpu: {{ .Values.counselingtoolsservice.resources.requests.cpu }}
              {{- end}}
            {{- end }}
            {{- if .Values.counselingtoolsservice.resources.limits }}
            limits:
              {{- if .Values.counselingtoolsservice.resources.limits.memory }}
              memory: {{ .Values.counselingtoolsservice.resources.limits.memory }}
              {{- end}}
              {{- if .Values.counselingtoolsservice.resources.limits.cpu }}
              cpu: {{ .Values.counselingtoolsservice.resources.limits.cpu }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always
  {{- end }}