apiVersion: v1
data:
  # General
{{- if .Values.global.enableTls }}
  APP_BASE_URL: "https://{{ .Values.global.domainName }}"
{{- else }}
  APP_BASE_URL: "http://{{ .Values.global.domainName }}"
{{- end }}
  # Spring/Database
  SPRING_PROFILES_ACTIVE: {{ .Values.uploadServiceSpringProfilesActive }}
  # Keycloak
  KEYCLOAK_AUTH_SERVER_URL: {{ .Values.keycloakAuthServerUrl }}
  KEYCLOAK_REALM: {{ .Values.keycloakRealm }}
  KEYCLOAK_PRINCIPAL_ATTRIBUTE: {{ .Values.keycloakPrincipalAttribute }}
  KEYCLOAK_RESOURCE:  {{ .Values.uploadServiceKeycloakResource }}
  KEYCLOAK_CORS: "false"
  KEYCLOAKSERVICE_ADMIN_CLIENTID: {{ .Values.keycloakserviceAdminClientid }}
  KEYCLOAKSERVICE_APP_CLIENTID: {{ .Values.keycloakserviceAppClientid }}
  # Rocket.Chat
  ROCKET_CHAT_API_URL: "http://rocketchat.{{ .Release.Namespace }}:3000/api/v1"
  ROCKET_CREDENTIALSCHEDULER_CRON: {{ .Values.rocketCredentialschedulerCron }}
  # Services
  USER_SERVICE_API_URL: "http://userservice.{{ .Release.Namespace }}:8080"
  USER_SERVICE_API_LIVEPROXY_URL: "http://userservice.{{ .Release.Namespace }}:8080"
  # CSRF
  CSRF_HEADER_PROPERTY: {{ .Values.csrfHeaderProperty }}
  CSRF_COOKIE_PROPERTY: {{ .Values.csrfCookieProperty }}
  {{- if .Values.global.useExternalMariaDb }}
  SPRING_DATASOURCE_URL: "jdbc:mariadb://{{ .Values.global.mariaDbHost }}:3306/uploadservice"
  {{- else }}
  SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/uploadservice"
  {{- end }}
  CSRF_WHITELIST_HEADER_PROPERTY: {{ .Values.csrfWhitelistHeaderProperty }}
  MULTITENANCY_ENABLED: {{ .Values.global.multitenancyEnabled | quote }}
  FEATURE_MULTITENANCY_WITH_SINGLE_DOMAIN_ENABLED: {{ .Values.global.multitenancyWithSingleDomainEnabled | quote }}
  TENANT_SERVICE_API_URL: "http://tenantservice.{{ .Release.Namespace }}:8080"
  {{- if .Values.zipkin.enabled }}
  SPRING_ZIPKIN_BASE_URL: "{{ .Values.zipkin.baseUrl }}"
  {{- end }}
  SPRING_SLEUTH_WEB_ENABLED: {{ .Values.zipkin.enabled | default false | quote }}
  SPRING_SLEUTH_SAMPLER_PERCENTAGE: {{ .Values.zipkin.samplerPercentage | default "1.0" | quote }}
  {{- if .Values.zipkin.enabled }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "{{ .Values.zipkin.tracing.endpoint }}"
  {{- end }}
  MANAGEMENT_TRACING_ENABLED: {{ .Values.zipkin.enabled | default false | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: "{{ .Values.keycloakAuthServerUrl }}/realms/{{ .Values.keycloakRealm }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: "{{ .Values.keycloakAuthServerUrl }}/realms/{{ .Values.keycloakRealm }}/protocol/openid-connect/certs"
  SPRING_JWT_AUTH_CONVERTER_RESOURCEID: "{{ .Values.keycloakserviceAppClientid }}"

kind: ConfigMap
metadata:
  labels:
    io.kompose.service: uploadservice-{{ .Release.Name }}-env
  name: uploadservice-{{ .Release.Name }}-env
