apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consultingtypeservice
  name: consultingtypeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consultingtypeservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/database_network: "true"
        io.kompose.network/frontend_network: "true"
        io.kompose.network/service_network: "true"
        io.kompose.service: consultingtypeservice
    spec:
      hostAliases:
        - ip: {{ .Values.global.dockerHostIp }}
          hostnames:
            - {{ .Values.global.domainName }}
      initContainers:
        - name: wait-for-keycloak
          image: busybox
          command: [ "sh", "-c", "until nc -z keycloak 8080 > /dev/null; do echo Waiting for keycloak.; sleep 5; done;" ]
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: CONSULTINGTYPESERVICE_SPRING_DATASOURCE_PASSWORD
                  name: consultingtypeservice-secret-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: CONSULTINGTYPESERVICE_SPRING_DATASOURCE_USERNAME
                  name: consultingtypeservice-secret-{{ .Release.Name }}-env
            - name: SPRING_LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_LIQUIBASE_PASSWORD
                  name: consultingtypeservice-secret-{{ .Release.Name }}-env
            - name: SPRING_LIQUIBASE_USER
              valueFrom:
                secretKeyRef:
                  key: SPRING_LIQUIBASE_USER
                  name: consultingtypeservice-secret-{{ .Release.Name }}-env
            - name: CONSULTING_TYPES_JSON_PATH
              valueFrom:
                configMapKeyRef:
                  key: CONSULTING_TYPES_JSON_PATH
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: CSRF_COOKIE_PROPERTY
              valueFrom:
                configMapKeyRef:
                  key: CSRF_COOKIE_PROPERTY
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: CSRF_HEADER_PROPERTY
              valueFrom:
                configMapKeyRef:
                  key: CSRF_HEADER_PROPERTY
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: TENANT_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: TENANT_SERVICE_API_URL
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: MULTITENANCY_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: MULTITENANCY_ENABLED
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  key: JAVA_OPTS
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: APP_BASE_URL
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATA_MONGODB_URI
                  name: consultingtypeservice-secret-{{ .Release.Name }}-env
            - name: KEYCLOAK_CORS
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAK_CORS
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_PRINCIPAL_ATTRIBUTE
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAK_PRINCIPAL_ATTRIBUTE
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: KEYCLOAKSERVICE_ADMIN_CLIENTID
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAKSERVICE_ADMIN_CLIENTID
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: KEYCLOAKSERVICE_APP_CLIENTID
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAKSERVICE_APP_CLIENTID
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAK_AUTH_SERVER_URL
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_REALM
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAK_REALM
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: KEYCLOAK_RESOURCE
              valueFrom:
                configMapKeyRef:
                 key: KEYCLOAK_RESOURCE
                 name: consultingtypeservice-{{ .Release.Name }}-env
            - name: FEATURE_MULTITENANCY_WITH_SINGLE_DOMAIN_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: FEATURE_MULTITENANCY_WITH_SINGLE_DOMAIN_ENABLED
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: SETTING_MAIN_TENANT_SUBDOMAIN_FOR_SINGLE_DOMAIN_MULTITENANCY
              valueFrom:
                configMapKeyRef:
                  key: SETTING_MAIN_TENANT_SUBDOMAIN_FOR_SINGLE_DOMAIN_MULTITENANCY
                  name: consultingtypeservice-{{ .Release.Name }}-env
            {{- if .Values.zipkin.enabled }}
            - name: SPRING_ZIPKIN_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_ZIPKIN_BASE_URL
                  name: consultingtypeservice-{{ .Release.Name }}-env
            {{- end }}
            - name: SPRING_SLEUTH_WEB_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SLEUTH_WEB_ENABLED
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: SPRING_SLEUTH_SAMPLER_PERCENTAGE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SLEUTH_SAMPLER_PERCENTAGE
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI
                  name: consultingtypeservice-{{ .Release.Name }}-env
            - name: SPRING_JWT_AUTH_CONVERTER_RESOURCEID
              valueFrom:
                configMapKeyRef:
                  key: SPRING_JWT_AUTH_CONVERTER_RESOURCEID
                  name: consultingtypeservice-{{ .Release.Name }}-env
          image:  {{ .Values.consultingTypeServiceImageName }}:{{ .Values.consultingTypeServiceImageVersion }}
          imagePullPolicy: Always
          name: consultingtypeservice
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /{{ .Values.consultingTypesJsonPath }}
              name: consulting-type-settings
          {{- if .Values.consultingtypeservice }}
          {{- if .Values.consultingtypeservice.resources }}
          resources:
            {{- if .Values.consultingtypeservice.resources.requests }}
            requests:
              {{- if .Values.consultingtypeservice.resources.requests.memory }}
              memory: {{  .Values.consultingtypeservice.resources.requests.memory }}
              {{- end }}
              {{- if .Values.consultingtypeservice.resources.requests.cpu }}
              cpu: {{ .Values.consultingtypeservice.resources.requests.cpu }}
              {{- end }}
            {{- end }}
            {{- if .Values.consultingtypeservice.resources.limits }}
            limits:
              {{- if .Values.consultingtypeservice.resources.limits.memory }}
              memory: {{ .Values.consultingtypeservice.resources.limits.memory }}
              {{- end }}
              {{- if .Values.consultingtypeservice.resources.limits.cpu }}
              cpu: {{ .Values.consultingtypeservice.resources.limits.cpu }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always
      volumes:
        - name: consulting-type-settings
          configMap:
            name: consultingtypeservice-settings-{{ .Release.Name }}-configmap