apiVersion: v1
kind: Secret
metadata:
  name: messageservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  SPRING_LIQUIBASE_USER: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  MESSAGESERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.messageServiceSpringDatasourceUsername | b64enc | quote }}
  MESSAGESERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.messageServiceSpringDatasourcePassword | b64enc | quote }}
  ROCKET_TECHNICAL_USERNAME:  {{ .Values.rocketTechnicalUsername  | b64enc | quote }}
  ROCKET_TECHNICAL_PASSWORD:  {{ .Values.rocketTechnicalPassword  | b64enc | quote }}
  ROCKET_SYSTEMUSER_USERNAME: {{ .Values.rocketSystemuserUsername | b64enc | quote }}
  ROCKET_SYSTEMUSER_PASSWORD: {{ .Values.rocketSystemuserPassword | b64enc | quote }}
  SERVICE_ENCRYPTION_APPKEY: {{ .Values.serviceEncryptionAppkey | b64enc | quote }}
  SENTRY_DSN: {{ .Values.sentry.dsn | b64enc | quote }}
